# Generated by Django 3.2.7 on 2021-11-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ignoreblockuser',
            unique_together={('to', 'by')},
        ),
        migrations.AlterUniqueTogether(
            name='reportuser',
            unique_together={('reported_user', 'reported_by')},
        ),
    ]
