# Generated by Django 3.2.7 on 2021-10-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ignoreblockuser',
            old_name='to_user',
            new_name='to',
        ),
    ]
