# Generated by Django 3.2.7 on 2021-11-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211122_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='blocked/ignored by')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='blocked/ignored user')),
            ],
            options={
                'unique_together': {('to_user', 'by_user')},
            },
        ),
        migrations.DeleteModel(
            name='IgnoreBlockUser',
        ),
    ]
