# Generated by Django 3.2.7 on 2021-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211122_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
