# Generated by Django 3.2.7 on 2021-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211125_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='admin@email.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
