# Generated by Django 3.2.7 on 2022-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_version', models.DecimalField(decimal_places=1, max_digits=3)),
                ('latest_version', models.DecimalField(decimal_places=1, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
