# Generated by Django 3.2.7 on 2022-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioninfo',
            name='latest_version',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='versioninfo',
            name='min_version',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
