# Generated by Django 3.2.7 on 2022-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20220121_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioninfo',
            name='latest_version',
        ),
        migrations.RemoveField(
            model_name='versioninfo',
            name='min_version',
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='latest_build_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='min_build_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
