# Generated by Django 3.2.7 on 2021-10-11 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20211011_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='ViewPost',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='duration_type',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='privacy',
            field=models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='privacy',
            field=models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')]),
        ),
    ]
