# Generated by Django 3.2.7 on 2021-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211011_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='privacy',
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'closed'), (1, 'open')], default=0),
            preserve_default=False,
        ),
    ]
