# Generated by Django 3.2.7 on 2021-10-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211011_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
