# Generated by Django 3.2.7 on 2021-10-14 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_favouritevocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='post.subscription'),
        ),
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning', models.TextField(verbose_name='comments/reasoning')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment by reviewer')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'reviewed')], default=0)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
