# Generated by Django 3.2.7 on 2021-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20211014_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment_type',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'image'), (2, 'audio'), (3, 'video')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')], default=1),
        ),
    ]
