# Generated by Django 3.2.7 on 2021-11-17 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20211116_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.playlist'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.subscription'),
        ),
    ]
