# Generated by Django 3.2.7 on 2021-10-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20211014_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='privacy',
            field=models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'closed'), (1, 'open')], default=1),
        ),
    ]
