# Generated by Django 3.2.7 on 2021-11-22 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20211118_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('owner', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='favouritevocabulary',
            unique_together={('user', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed_user', 'followed_by')},
        ),
        migrations.AlterUniqueTogether(
            name='ignorepost',
            unique_together={('ignored_post', 'ignored_by')},
        ),
        migrations.AlterUniqueTogether(
            name='likecomment',
            unique_together={('liker', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('liker', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='reportpost',
            unique_together={('post', 'reported_by')},
        ),
        migrations.AlterUniqueTogether(
            name='saveplaylist',
            unique_together={('owner', 'playlist')},
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('subscriber', 'subscription')},
        ),
        migrations.AlterUniqueTogether(
            name='viewpost',
            unique_together={('viewer', 'post')},
        ),
    ]
