# Generated by Django 3.2.7 on 2021-10-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20211014_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='saveplaylist',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='subscriber',
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewpost',
            name='user',
        ),
        migrations.AddField(
            model_name='likecomment',
            name='liker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likepost',
            name='liker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewpost',
            name='viewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterField(
            model_name='viewpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
