# Generated by Django 3.2.7 on 2021-10-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20211014_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followed_user',
        ),
    ]
