# Generated by Django 3.2.7 on 2021-11-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_full_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
