# Generated by Django 3.2.7 on 2021-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_ignorepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_simplified_chinese',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_traditional_chinese',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='english_meaning_article',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='meaning_words',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pin_yin_words',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sim_spaced_datastore_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sticker_position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sticker_position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sticker_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='story_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='story_difficulty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='story_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='story_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_on_post',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='timing_simplified_chinese',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='timing_traditional_chinese',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='trad_spaced_datastore_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_simplified_chinese',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_traditional_chinese',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
