# Generated by Django 3.2.7 on 2021-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20211130_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='indonesian_meaning_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='korean_meaning_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tagalog_meaning_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
