# Generated by Django 3.2.7 on 2021-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20211206_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'like'), (1, 'comment'), (2, 'follow'), (3, 'subscribe'), (4, 'announcement')], default=4),
        ),
    ]
