# Generated by Django 3.2.7 on 2021-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_notification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment_type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Image'), (2, 'Audio'), (3, 'Video')], default=0),
        ),
    ]
