# Generated by Django 3.2.7 on 2022-01-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_alter_viewpost_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='playlist',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='post.HashTag'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='post.HashTag'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='post.HashTag'),
        ),
    ]
