# Generated by Django 3.2.7 on 2022-01-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20220102_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
