# Generated by Django 3.2.7 on 2022-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20220210_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritevocabulary',
            old_name='meaning',
            new_name='eng',
        ),
        migrations.AddField(
            model_name='favouritevocabulary',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favouritevocabulary',
            name='sim',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouritevocabulary',
            name='trad',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favouritevocabulary',
            name='pinyin',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='favouritevocabulary',
            name='word',
            field=models.CharField(max_length=2000),
        ),
    ]
