# Generated by Django 3.2.7 on 2022-02-22 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0028_auto_20220221_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(default=420, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='account.user'),
            preserve_default=False,
        ),
    ]
