# Generated by Django 3.2.7 on 2022-03-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_notification_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_cantonese_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='has_mandarin_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='voice_over_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'woman'), (1, 'man'), (2, 'child'), (3, 'custom')], default=0),
            preserve_default=False,
        ),
    ]
