# Generated by Django 3.2.7 on 2022-03-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_auto_20220309_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='has_cantonese_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='has_mandarin_audio',
            field=models.BooleanField(default=False),
        ),
    ]
