# Generated by Django 3.2.7 on 2022-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20220309_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
