# Generated by Django 3.2.7 on 2022-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_post_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
