# Generated by Django 3.2.7 on 2022-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_alter_post_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generate_voiceovers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice_over_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'woman'), (1, 'man'), (2, 'child'), (3, 'custom')], null=True),
        ),
    ]
