# Generated by Django 3.2.7 on 2022-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20220313_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hsk_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice_over_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'woman-woman'), (1, 'man-man'), (2, 'woman-child'), (3, 'custom-woman'), (4, 'women-custom'), (5, 'custom-custom')], null=True),
        ),
    ]
