# Generated by Django 3.2.7 on 2021-10-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputanswerquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_inputanswerquestion_related', related_query_name='quiz_inputanswerquestions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_multiplechoicequestion_related', related_query_name='quiz_multiplechoicequestions', to='quiz.quiz'),
        ),
    ]
