# Generated by Django 3.2.7 on 2021-11-01 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceattempt',
            name='question_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_attempts', to='quiz.multiplechoicequestionattempt'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='examinee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_quizattempt_related', related_query_name='quiz_quizattempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
