# Generated by Django 3.2.7 on 2021-11-01 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20211101_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputanswerquestionattempt',
            name='quiz_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_inputanswerquestionattempt_related', related_query_name='quiz_inputanswerquestionattempts', to='quiz.quizattempt'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionattempt',
            name='quiz_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_multiplechoicequestionattempt_related', related_query_name='quiz_multiplechoicequestionattempts', to='quiz.quizattempt'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='examinee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
