# Generated by Django 3.2.7 on 2021-11-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20211101_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestionattempt',
            name='selected_choices',
            field=models.ManyToManyField(related_name='selected_choices', to='quiz.Choice'),
        ),
        migrations.DeleteModel(
            name='ChoiceAttempt',
        ),
    ]
