# Generated by Django 3.2.7 on 2021-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211103_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestionattempt',
            name='selected_choices',
            field=models.ManyToManyField(related_name='questions_selected_choices', to='quiz.Choice'),
        ),
    ]
