# Generated by Django 3.2.7 on 2021-11-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20211106_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='inputanswerquestion',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['created_at']},
        ),
    ]
