# Generated by Django 3.2.7 on 2022-01-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20211130_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inputanswerquestion',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputanswerquestionattempt',
            name='points_achieved',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionattempt',
            name='points_achieved',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
