# Generated by Django 3.2.7 on 2022-01-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_rename_dictionary_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='de',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='eng',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='es',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='hu',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='ind',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='ko',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='sim',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='tl',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='trad',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='ur',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='vi',
            field=models.CharField(max_length=1000),
        ),
    ]
